# Lecture 08: Functions 

In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions 

**The Anatomy of a Function:**
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
    return return_expression
```

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [2]:
def triple(x):
    return 3 * x

In [3]:
triple(3)

9

In [4]:
triple(4)

12

In [5]:
triple(5)

15

In [6]:
triple(10)

30

In [7]:
triple('10')

'101010'

In [8]:
x = 100
triple(x) 
# triple(100) = 3 * 100

300

In [9]:
triple(x * 5) # triple(100 * 5) = triple (500) = 3 * 500 = 1500

1500

We can also assign a value to a name, and call the function on the name:

## Functions are Type-Agnostic  ## 
Try feeding it a float

In [10]:
triple(4.0)

12.0

Try feeding it a string

Try feeding it an array

In [12]:
triple(make_array(0,1,2,3))
# (3 * 0, 3 * 1, 3 * 2, 3 * 3) = (0, 3, 6, 9)

array([0, 3, 6, 9])

In [14]:
np.arange(4)
triple(np.arange(4))

array([0, 3, 6, 9])

Try feeding it a table

In [18]:
my_new_table = Table().with_column('values',np.arange(4))
triple(my_new_table)

TypeError: unsupported operand type(s) for *: 'int' and 'Table'

In [19]:
values_array = my_new_table.column('values') # if we want to multiply everything in our table by 3
# we first need to decide which column we want to do the multiplication to
# then extract that column as an array using .column
triple(values_array)

array([0, 3, 6, 9])

In [21]:
my_new_table.with_column('tripled', triple(values_array))
# once we've multiplied, or used triple, then we can add that back in the table as a new column
#using .with_column

values | tripled
0      | 0
1      | 3
2      | 6
3      | 9

### Discussion Question 
What does this function do? What kind of input does it  take? What output will it give? What's a reasonable name?


```python
def f(s):     
    return np.round(s / sum(s) * 100, 2)
```

In [27]:
make_array(0,1,2,3)

array([0, 1, 2, 3])

In [25]:
s = make_array(0,1,2,3)
s / sum(s) # find the proportion of each element

array([ 0.        ,  0.16666667,  0.33333333,  0.5       ])

Let's rename the function to what it does

In [28]:
s / sum(s) * 100 #percentage


array([  0.        ,  16.66666667,  33.33333333,  50.        ])

In [30]:
np.round(s / sum(s) * 100, 2)

array([  0.  ,  16.67,  33.33,  50.  ])

In [ ]:
def percentage_of_totals(s):     
    ''' multi-line comment
    whenever you write your own function
    take a moment to describe what your input should be, data type
    also what will it return (output)
    s is an array
    and we find the percentage of total sum for each element in our array, s

    we return an array, of each element's percentage of total sum
    '''
    return np.round(s / sum(s) * 100, 2)

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

In [32]:
def hypotenuse(x, y): # function header, it always ends with a colon
    # which tells python that the next line is our function body
    # function body has the instructions of what we'll do with our inputs x and y
    '''
    our inputs x and y are ints or floats, denoting lengths of right-angle sides
    hypotenuse returns a single value (int/float), denoting the length of the hypotenuse of the right triangle
    '''
    
    h_squared = x**2 + y**2 # h^2 = x^2 + y^2
    return np.sqrt(h_squared) #square root of h^2 = h
    

In [34]:
hypotenuse(1,1)

1.4142135623730951

In [33]:
np.sqrt(2)

1.4142135623730951

In [36]:
hypotenuse(2,2)

2.8284271247461903

In [35]:
np.sqrt(2**2 + 2**2)

2.8284271247461903

In [31]:
np.sqrt(4)

2.0

We could've typed the body all in one line. Do you find this more readable or less readable than the original version?

### Example: A function that takes the year of birth of a person and produces their age in years. ###

In [37]:
def age(year): # think about your birth year
    age_years = 2024 - year
    return age_years
    

In [38]:
age(2019)

5

In [39]:
age(2004)

20

In [40]:
age(2003)

21

In [41]:
age(1996)


28

Now add some bells and whistles:  Take person's name and year of birth (two arguments). Produce a sentence that states how old they are.

In [42]:
def name_and_age(name, year):
    '''
    two arguments: name should be a string, year should be their DOB
    find their current age (or what age they'll turn this year 
    return a sentence (string format) the person's name and how old they'll be this year
    '''
    age_years = 2024 - year
    return name + ' will be ' + str(age_years) + ' years old in 2024.' # Anushka will be 21 years old in 2024.

In [43]:
name_and_age('Anushka', 2003)


'Anushka will be 21 years old in 2024.'

In [44]:
name_and_age('SueAnn', 1996)

'SueAnn will be 28 years old in 2024.'

In [45]:
name_and_age('Shai', 2019)

'Shai will be 5 years old in 2024.'

## Apply ##

In [46]:
staff = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
staff

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

- we could run the age function on every element of the birth year column  
- and then create an array. 

In [47]:
age(staff.column('Birth Year').item(0))

39

In [48]:
2024 - 1985

39

Let's instead `apply` the `age` and `name_and_age` function to a column

In [50]:
staff_ages = staff.apply(age, 'Birth Year')
# apply the age function to the 'Birth Year' column in the staff Table

In [56]:
staff = staff.with_column('Ages', staff_ages)

In [62]:
staff_sentences = staff.apply(name_and_age, 'Person', 'Birth Year')

In [58]:
staff = staff.with_column('Statements', staff_sentences)

In [59]:
staff

Person  | Birth Year | Ages | Statements
Jim     | 1985       | 39   | Jim will be 39 years old in 2024.
Pam     | 1988       | 36   | Pam will be 36 years old in 2024.
Michael | 1967       | 57   | Michael will be 57 years old in 2024.
Creed   | 1904       | 120  | Creed will be 120 years old in 2024.

In [60]:
staff_ages = staff.apply(age,'Birth Year')


TypeError: unsupported operand type(s) for -: 'int' and 'str'

In [63]:
def are_you_jim(name):
    '''
    our argument name will be a staff name (from the office)
    we are checking whether or not they are Jim
    return a boolean value of True or False, True if Jim, False if not
    '''
    true_or_false = (name == 'Jim')
    return true_or_false

In [64]:
are_you_jim('Jim')

True

In [65]:
are_you_jim('jim')
# bonus, can you rewrite the function above to accept lowercase jim too?

False

In [66]:
are_you_jim(' jim ')
# and also jim with spaces?

False

In [67]:
are_you_jim('creed')

False

In [70]:
staff.with_column('Are you Jim?', staff.apply(are_you_jim, 'Person'))

Person  | Birth Year | Ages | Statements                            | Are you Jim?
Jim     | 1985       | 39   | Jim will be 39 years old in 2024.     | True
Pam     | 1988       | 36   | Pam will be 36 years old in 2024.     | False
Michael | 1967       | 57   | Michael will be 57 years old in 2024. | False
Creed   | 1904       | 120  | Creed will be 120 years old in 2024.  | False